#
# Make Xinu's digital signal processing library
#

# Name of this library
LIBNAME := libdsp

# C files to compile (.c)
CFILES  := linear2ulaw.c ulaw2linear.c

# Assembly files to compile (.S)
SFILES  :=

# Directory in which to place the output library, and
# location of common Makerules
LIBDIR	:= ..

include $(LIBDIR)/Makerules
